# Disable sudo to speed up the build
sudo: true

language: python

services:
  - docker

# Run the unit test
script:
  - pip install codecov
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose up --abort-on-container-exit --exit-code-from tester --build

# Push the results back to codecov
after_success:
  - codecov -f ./.reports/coverage.xml

deploy:
  provider: pypi
  user: Harlekuin
  password: "$pypipassword"
  on:
    branch: master
    python: 3.6
