# Disable sudo to speed up the build
sudo: true

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

# Run the unit test
script:
  - docker-compose up --abort-on-container-exit --exit-code-from tester --build

# Push the results back to codecov
after_success:
  - codecov -f ./.reports/.coverage

deploy:
  provider: pypi
  user: Harlekuin
  password: "$pypipassword"
  on:
    branch: master
    python: 3.6
