connections:

  - name: my-sqlite-database
    driver: sqlite:///
    connection: /tmp/database.db

  - name: my-mysql-database
    driver: mysql+pymysql://
    connection: user:password@mysql:3306/testdatabase

  - name: my-postgresql-database
    driver: postgresql+psycopg2://
    connection: user:password@postgres:5432/testdatabase
